version: 0.0
os: linux

files:
  - source: frontend
    destination: /home/ubuntu/angel/frontend

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu

  BeforeInstall:
    # 1) Install Node 20.x as root
    - location: scripts/setup_node.sh
      timeout: 300
      runas: root

    # 2) Stop the old app
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu

  AfterInstall:
    # 3) Fix ownership now that files exist
    - location: scripts/fix_perms.sh
      timeout: 60
      runas: root

    # 4) Run npm install/build
    - location: scripts/install.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ubuntu
